{{- if .Values.cronjob.enabled -}}
  {{- $root := . -}}
  {{- $appname := printf "%s" (include "name" .) -}}
  {{- $cronJobName :=  printf "%s-%s" (include "name" .) "cron" -}}
  {{- range $key, $value := .Values.cronjob.spec }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    helm.sh/chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
    cronjob: {{ $cronJobName }}
  name: {{ $cronJobName }}-{{ $key }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      name: {{ $cronJobName }}-{{ $key }}
      labels:
        helm.sh/chart: "{{$root.Chart.Name}}-{{$root.Chart.Version}}"
        cronjob: {{ $cronJobName }}
    spec:
      template:
        spec:
          containers:
          - name: {{ $key }}
            command: 
            {{- range $value.command}}
            - {{ . }}
            {{- end }}
            args:
            {{- range $value.args}}
            - {{ . }}
            {{- end }}
            {{- if $root.Values.configmap }}
            envFrom:
            - configMapRef:
                name: {{ $appname }}
            {{- end }}
            env:
            {{- if $root.Values.secrets }}
            {{- range $key, $value := $root.Values.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  key: {{ $value }}
                  name: {{ $appname }}
            {{- end }}
            {{- end }}
            image: {{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}
            imagePullPolicy: Always
        {{- if $root.Values.nodeSelector }}
          nodeSelector:
          {{ toYaml $root.Values.nodeSelector | indent 8 }}
        {{- end }}
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: {{ default "1 * * * *" $value.schedule | quote }}
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  suspend: false
  {{- end -}}
{{- end -}}