{{- if .Values.deploySecretNexus -}}
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1cy5lZ3QtdWEubG9jIjp7InBhc3N3b3JkIjoiU2VkbmdybGthZ3loaWV1eTEiLCJ1c2VybmFtZSI6InJhbmNoZXIifX19
kind: Secret
metadata:
  name: regsecret
type: kubernetes.io/dockerconfigjson
{{- end -}}
