{{- if .Values.deploySecretHarbor -}}
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuZWd0LXVhLmNvbSI6eyJ1c2VybmFtZSI6Imt1YmUiLCJwYXNzd29yZCI6Imt0U01LUXBUcGwwSlhabEQiLCJlbWFpbCI6ImFkbWluaXN0cmF0b3JAZWd0LXVhLmxvYyIsImF1dGgiOiJhM1ZpWlRwcmRGTk5TMUZ3VkhCc01FcFlXbXhFIn19fQ==
kind: Secret
metadata:
  name: regsecret
type: kubernetes.io/dockerconfigjson
{{- end -}}
