{{- $serviceDefaultName :=  printf "%s-%s" (include "name" .) "sv" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceDefaultName }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  ports:
{{- range $key, $value := .Values.service.ports }}
  - port: {{ default 80 $value.externalPort }}
    targetPort: {{ $value.internalPort }}
    type: {{ $value.protocol }}
    name: {{ $key }}
{{- end }}
  selector:
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
  type: "{{ .Values.service.type }}"
{{- if contains "LoadBalancer" .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
